import React from 'react';
import Head from 'next/head';
import Navbar from '@/components/organisms/navbar';
import ContentActivity from '@/components/organisms/contentActivity';
import ListEmpty from '@/components/molecules/listEmpty';
import ListTodo from '@/components/molecules/listTodo';

export default function detailTodoList() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col min-h-screen">
				<Navbar />
				<main className='bg-light grow'>
					<div className="container mx-auto">
						<ContentActivity />
						{/* <ListEmpty /> */}
						<ListTodo />
					</div>
				</main>
			</div>
		</>
	);
}
